package seedu.address.autocomplete;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import seedu.address.autocomplete.parser.AutoCompleteParser;

/** Contains utility methods for testing autocomplete component. */
public class AutoCompleteTestUtils {

    /**
     * Tests the possibilities generated by the stub against the list of possibilities expected
     * @param stub test input
     * @param generated list of generated output
     * @param possibilities expected possibilities output
     */
    public static void assertEqualsPossibilities(String stub, List<String> generated, String... possibilities) {
        List<String> expected = new ArrayList<String>();
        expected.addAll(Arrays.asList(possibilities));
        expected.add(stub);
        assertEquals(generated, expected);
    }

    /**
     * Tests the possibilities generated by the stub against the list of possibilities expected
     * @param stub test input
     * @param parser parser to test against
     * @param possibilities expected possibilities output
     */
    public static void assertParserPossibilities(String stub, AutoCompleteParser parser, String... possibilities) {
        AutoCompleteTestUtils.assertEqualsPossibilities(stub, parser.parseForPossibilities(stub), possibilities);
    }

}
