= Emil Koh - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:repoURL: https://github.com/CS2103AUG2017-T17-B3/main/tree/master

== Project: Circles
Circles is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 6 kLoC.

*Code Contributed*: [link:{repoURL}/collated/main/LimeFallacie.md[`Functional Code`]][link:{repoURL}/collated/test/LimeFallacie.md[`Test Code`]]

=== Enhancement Added: Sorting

==== External Behaviour

include::../UserGuide.adoc[leveloffset=+2, tag=sort]

==== Justification
As our target audience was University students, we felt the need to provide tools to organise the contacts list as one student can come across many
over the course of his studies. With the ability to organise contacts in an intuitive way, users would easily be able to locate contacts by scrolling through the list
rather than constantly using the `Find` command.

The command word `sort` is used to denote the sort, and the following word would decide how the list would be sorted.
As there are plenty of different ways to sort contacts, this implementation was chosen to allow modularity for the inclusion of more ways to sort the list in the future.

==== Implementation

include::../DeveloperGuide.adoc[leveloffset=+2, tag=sort]

=== Enhancement Added: Listing by tags

==== External Behaviour

include::UserGuide.adoc[leveloffset=+2, tag=listtag]

==== Justification
This allows the user more flexibility in searching for several contacts with similar tags, a major quality of life improvement.

==== Implementation

include::../DeveloperGuide.adoc[leveloffset=+2, tag=listtag]

=== Enhancement Added: Export/Import contacts list

==== External Behaviour

include::../UserGuide.adoc[leveloffset=+2, tag=expimp]

==== Justification
Exporting and importing of the contacts list allows the user more portability.
All the user's data can be easily transferred between terminals and can also be easily backed up.

==== Implementation

//to continue after include implementation of export/import in Dev Guide


