= Alpheus Lim - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Sort

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification

Users will want to view the list of contacts sorted for them based on their name, phone, email or address.
Some users find the contact they want by scrolling through the list as opposed to typing and this will aid them.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sort]

#End of Extract#

---

=== Enhancement Added: First time tutorial

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tutorial]

#End of Extract#

---

==== Justification

Currently when new users launch Bluebird for the first time, they will be lost as to what Bluebird has to offer and also what different UI panels mean.
Therefore, there is a need to provide first time users of Bluebird a step-by-step tutorial on how Bluebird works.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tutorial]

#End of Extract#

---

=== Enhancement Added: Enhanced Find

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=find]

#End of Extract#

---

==== Justification

Users may want to search for the contact not just by their names, but also by their phone number, email
, address and also their tags as well. This enhancement gives users the choice to decide how they would want
to search for the contact they want.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=find]

#End of Extract#

---

=== Enhancement Added: Pin/Unpin contact

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=pinunpin]

#End of Extract#

---

==== Justification

Users may have some important contacts that they need to have quick access to at all times. Hence,
this feature will solve the problem for them.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=pinunpin]

#End of Extract#

---



=== Enhancement Proposed:

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Updated the UI of Bluebird (Pull requests https://github.com[#14], https://github.com[#58], https://github.com[#73], https://github.com[#118]
, https://github.com[#134], https://github.com[#143], https://github.com[#144], https://github.com[#205], https://github.com[#208])
* Updated a help overlay for Bluebird (Pull requests https://github.com[#189], https://github.com[#208])

