= Calvin Tantio - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

ConTag is an efficient and feature-packed desktop address book application for the most demanding business users and busiest frequent travellers. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java.

*Code contributed*: [https://github.com/CS2103AUG2017-T15-B2/main/blob/master/collated/main/CT15.md[Functional code]] [https://github.com/CS2103AUG2017-T15-B2/main/blob/master/collated/test/CT15.md[Test code]]

=== Enhancement Added: Displaying the Usage of Specific Command

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=help]

#End of Extract#

---

==== Justification

ConTag supports various commands with different command formats. This makes it difficult for new users to remember how each command is used. Displaying the format of a specific command will save users the trouble to go through the user guide repeatedly. This enhancement serves as a quick reminder for the users, catered especially towards new users.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=help]

#End of Extract#

---
