= Chia Cherng Hann - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: The Myth's Book
The Myth's Book is an address book dedicated for university students to store useful information such
as websites, phone numbers and emails of the people around them for personal usage. The application helps students
to keep track of birthday dates and upcoming events through a calendar and facilitate convenient access to their friend's website
and even Google Maps location through the in-built browser panel in the application. Furthermore, there are many
useful tools such as finding group tags (e.g. friends, neighbours) and switching themes for better user preference and usability.

The Myth's Book is a `Command Line Input` based software which helps caters to students who are efficient and comfortable
in typing out command line inputs to manipulate with information of their contacts in the address book.
The Myth's Book is a software application that is coded in `Java` programming language.

*Code contributed*: [https://github.com/CS2103AUG2017-T15-B3/main/blob/master/collated/main/chernghann.md[Functional code]] [https://github.com/CS2103AUG2017-T15-B3/main/blob/master/collated/test/chernghann.md[Test code]]

=== Enhancement Added: Add Events

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=addevent]

include::../UserGuide.adoc[tag=calendar]

#End of Extract#

---

==== Justification

As an address book targeted at University students in Singapore age between 18-24.
On average, an university students have to juggle between many commitments in school and out of school. Many of these young adults are actively involved in many events internally and externally.
Thus, the add event feature allos the users to be able to store and keep track of what events that are coming up and be able to plan and organise their schedule.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=addevent]

#End of Extract#

---

=== Enhancement Added: Calendar

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=calendar]

#End of Extract#

---

==== Justification

A Calendar User Interface will enhance the user's experience in using and organising their upcoming events. With a simple click on the calendar,
the user will be able to get to add the events and be shown to them on the calendar with it being populating with a different shade of colour.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=calendar]

#End of Extract#

---

=== Enhancement Proposed: Sending of Text Messages




=== Other contributions
* Acceptance Testing
- Provide suggestions for improvement (Pull request https://github.com/CS2103AUG2017-W09-B1/main/issues/121#event-1330982844[#121])
- Found a bug in implementation (Pull request https://github.com/CS2103AUG2017-W09-B1/main/issues/113[#113])
