= Darren Chin Jhun Pyng - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Purpose

This project portfolio displays the contributions and enhancements made to the software, The Myth's Book,
along with its justifications. The portfolio will first introduce The Myth's Book and subsequently talk
about the enhancements and contributions made by Darren Chin Jhun Pyng.

== Project: The Myth's Book
The Myth's Book is an address book dedicated for university students to store useful information such
as websites, phone numbers and emails of the people around them for personal usage. The application helps students
to keep track of birthday dates and upcoming events through a calendar and facilitate convenient access to their friend's website
and even Google Maps location through the in-built browser panel in the application. Furthermore, there are many
useful tools such as finding group tags (e.g. friends, neighbours) and switching themes for better user preference and usability.

The Myth's Book is a `Command Line Input` based software which helps caters to students who are efficient and comfortable
in typing out command line inputs to manipulate with information of their contacts in the address book.
The Myth's Book is a software application that is coded in `Java` programming language.

*Code contributed*: [https://github.com/CS2103AUG2017-T15-B3/main/blob/master/collated/main/DarrenCzen.md[Functional code]] [https://github.com/CS2103AUG2017-T15-B3/main/blob/master/collated/test/DarrenCzen.md[Test code]]

---
=== Enhancement Added: Sort Command, Sort Names Alphabetically

Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/46[#46]

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sort]

#End of Extract#

---

=== Enhancement Added: Access Command, Accessing a website of a contact
Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/77[#77]

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=access]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=access]

#End of Extract#

---

=== Enhancement Added: Location Command, Locate an address of a user
Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/79[#79]

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=locate]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=locate]

#End of Extract#

---


=== Enhancement: Add Command, Optional fields
Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/99[#99], https://github.com/CS2103AUG2017-T15-B3/main/pull/96[#96]

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=add]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

---


=== Enhancement: Website field for Person Class
Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/57[#57]

==== External behavior

---

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

---

=== Enhancement: Allow inputted names to become capitalized fully

Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/123/commits/cf57e5e78374ec3ee69125e8342ed27c9efa06da[#123]

==== External behavior

---

---
=== Enhancement: Alias for basic commands

Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/34[#34]

==== External behavior

---

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

---

=== Enhancement proposed: Toggling of Person List and Events List

==== External behavior

---

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

=== Other contributions

* Wrote introduction and about of The Myth's Book for User Guide and Developer Guide. (Pull request https://github.com/CS2103AUG2017-T15-B3/main/pull/91[#91])
* Change structure of software's user guide and updated preface of most sections in user guide. (Pull request https://github.com/CS2103AUG2017-T15-B3/main/pull/123[#123])
* Added prefix table for Add Command in user guide. (Pull request https://github.com/CS2103AUG2017-T15-B3/main/pull/123[#123])
* Updated software's user guide to be more user friendly and user focused. (Pull request https://github.com/CS2103AUG2017-T15-B3/main/pull/134[#134])
* Updated software's developer guide to showcase more user stories. (Pull request https://github.com/CS2103AUG2017-T15-B3/main/pull/35[#35], https://github.com/CS2103AUG2017-T15-B3/main/pull/53[#53])
* Wrote additional tests to test hashcode of person's attributes to increase test coverage (Pull requests https://github.com/CS2103AUG2017-T15-B3/main/pull/96[#96])

==== Contribution to Acceptance Testing: HitMeUp (CS2103AUG2017-W14-B3)

*Suggestion/Bug Finding contributed*:

1. Provided suggestion for sort command to be non case-sensitive.
(Issue #114 - https://github.com/CS2103AUG2017-W14-B3/main/issues/114[Suggestion - sort])

2. Provided suggestion for select command to show a user's twitter/instagram instead of google search.
(Issue #109 - https://github.com/CS2103AUG2017-W14-B3/main/issues/109[Suggestion for select function])

3. Provided suggestion for user guide to show better user guidance for email command.
(Issue #106 - https://github.com/CS2103AUG2017-W14-B3/main/issues/106[Suggestion - user guide for email function ])

4. Provided suggestion/bug fix for birthday inputted to account for leap year so that all contacts can have their birthday properly accounted for.
(Issue #105 - https://github.com/CS2103AUG2017-W14-B3/main/issues/105[Bug for Birthday])
