= Derek Nam - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Personal Information Manager Program (PIMP)
Personal Information Manager Program (PIMP) is a command line interface (CLI) address book that allows you to store your contacts. You can use PIMP to add friends, add specific tags to them, add their social media accounts (such as Facebook, Twitter, Instagram), or add remarks. You can search through the list of your contacts by typing specific names. For more advanced user, you can use regex to find your friends. Most of the functionality works by typing in single line commands.

PIMP v1.5 is available on any platform running Java 8.

=== Enhancement Added: Undo/Redo

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=statistics]

include::../UserGuide.adoc[tag=remark]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=statistics]

include::../DeveloperGuide.adoc[tag=remark]

#End of Extract#

---

=== Enhancement Proposed: []

{}

=== Other contributions

* Added total number of people and total recently added people to status bar (Pull requests https://github.com[#2], https://github.com[#75])
