= Nguyen Duy Son - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Gentleman's Guide
Gentleman's Guide is a desktop contact book application modified from the Address Book - Level 4, created by https://se-edu.github.io/[SE-EDU team].
It is designed to support the busy work life business-(gentle)men by helping them keep track of their contacts and reminding them about upcoming deadlines.
The interaction between user and Gentleman’s Guide is mostly done through a Command Line Interface (CLI). +
This application is written in Java, with its Graphical User Interface (GUI) created with JavaFX. It is written in Java, and has about 6 kLoC.

*About portfolio*:

*Code contributed*: [https://github.com/CS2103AUG2017-T09-B1/main/blob/master/collated/main/duyson98.md[Functional code]] [https://github.com/CS2103AUG2017-T09-B1/main/blob/master/collated/test/duyson98.md[Test code]]


=== Enhancement Added: Retrieve command, Tag/Untag/Retag commands, View command

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tagsmanipulation]

include::../UserGuide.adoc[tag=retrieve]

include::../UserGuide.adoc[tag=view]

#End of Extract#

---

==== Justification

`tag` and `retrieve` commands help you organize your address book by putting tags to contacts
and quickly get all contacts that have been assigned with a certain tag.

`untag` and `retag` commands allow you to remove the tags that are no longer needed and modify the existing tags
to reflect the changes in your relationship with the contact owners.

==== Implementation

---
#Start of Extract [from: User Guide]#

include::../DeveloperGuide.adoc[tag=taggingfunctions]

#End of Extract#

---

=== Enhancement Added: View contact profile

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=viewprofile]

#End of Extract#

---

==== Justification



==== Implementation

---
#Start of Extract [from: User Guide]#

include::../DeveloperGuide.adoc[tag=viewcommand]

#End of Extract#

---

=== Enhancement Proposed:

=== Other Contributions

* Added a digital clock to display date and time inside the GUI of the address book.

== Project
