= Ernest Ong YuHeng - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets
:collatedDir: ../../collated

== Project: MedNus
MedNus is a desktop address book application used by Medical Professionals. +
The user interacts with it using a CLI, and it has a GUI created with JavaFX. +
It is written in Java, and has about 6 kLoC.

*Code contributed*: +
link:{collatedDir}/main/Ernest.md[Functional code] +
link:{collatedDir}/test/Ernest.md[Test code] +

=== Purpose

This portfolio page is a documentation of my contributions to the project.
Details of each section includes:

* External behavior from User Guide
* Justification for each feature
* Details of Implementation from Developer Guide
+
The portfolio ends with:

* Proposed enhancements for v2.0
* Other Contributions

<<<

=== Enhancement Added: Add class Bloodtype

---

=== External Behaviour

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=bloodtype]

#End of Extract#

---

=== Justification

Blood type is one of important details of a patient that a doctor would require. +
The restriction of 12 inputs (case insensitive) is to limit incorrect inputs for blood type.

---

=== Implementation

#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=bloodtype]

#End of Extract#

---

=== Enhancement Added: Add List Bloodtype Command

---

=== External behaviour

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=listbloodtype]

#End of Extract#

---

=== Justification

This feature is to help doctors filter the blood types of the patients in their contact list. +
In times of emergency, being able to know which patients have which blood type can be critical +
such as when blood infusion is needed.

---

=== Implementation

#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=listbloodtype]

#End of Extract#

---

=== Enhancement Added: Add Relationship Command

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=relationship]

#End of Extract#

---

=== Justification

Knowing the family and relatives of a patient is important in times of emergency. +
There is almost always a need to find a way to contact people close to a patient.

---

=== Implementation

#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=relationship]

#End of Extract#

---

<<<

=== Enhancement Proposed for Version 2.0

* Command to store specific details of a condition tag (fracture, cancer) associated with a patient.
* This is to know specifically what condition is associated with a patient instead of a general condition.
* A medication field to know what a medication or treatment a patient currently have.
* This is to keep track if the current medication or treatment is effective for a patient.

=== Other contributions

* UI command output changes
* User Guide in collaboration with Jeremy
