= Lee Jun Yao Francis - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Ark
Ark is a parcel management software which users can interact with using a Command Line Interface, and it has a GUI
created with JavaFX. It is written in Java, and has about 14 kLoC.
You may access the Ark repository link:https://github.com/CS2103AUG2017-T16-B1/main[here].

Ark was built on top of link::https://github.com/nus-cs2103-AY1718S1/addressbook-level4[Addressbook - Level 4], an
addressbook application.

Below you can take a look at the segments of Ark that I've written. Functional code refers to code that
directly affects the performance and usability of Ark. Whereas test code refers to code written
to automatically test the features I've implemented.

*Code contributed*: [https://github.com/CS2103AUG2017-T16-B1/main/blob/master/collated/main/fustilio.md[Functional code]][https://github.com/CS2103AUG2017-T16-B1/main/blob/master/collated/test/fustilio.md[Test code]]

=== Enhancement Added: Delivery Dates field

==== External behavior

---

include::../UserGuide.adoc[tags=deliveryDate]

---

==== Justification

The delivery dates field is important as the list of parcels are sorted by delivery date
with the earliest at the top. This allows for the user to look at the more pertinent deliveries
immediately on start up.

==== Implementation

---

include::../DeveloperGuide.adoc[tags=deliveryDate]

---

=== Enhancement Added: Maintain Sorted Order Mechanism

==== External behavior

---

include::../UserGuide.adoc[tags=sortedList]

---

==== Justification

Having the list in sorted order allows the user to look at the more pertinent deliveries
more easily.

==== Implementation

---

include::../DeveloperGuide.adoc[tags=sortedList]

---

=== Enhancement Added: ArkBot: A Telegram Bot Interface for Ark

==== External behavior

---

include::../UserGuide.adoc[tags=ArkBot]

---

==== Justification

Practically speaking, a delivery man would not be able to use Ark on the go since it is a desktop application.
As such, I developed a https://core.telegram.org/bots[Telegram Bot] interface, enabling Ark to be accessed from
a mobile phone.

==== Implementation

---

include::../DeveloperGuide.adoc[tags=ArkBot]

---

=== Other contributions


== Project: GooBot

Over the summer of 2017, my partner and I developed a Telegram Bot generating framework using Node.js.
Our framework allows users without programming experience to create their own Finite State Machine style Telegram bots.
I specifically worked on data manipulation and created a simple HTML to allow users to manage their bots.

Goobot, which was created during the NUS Orbital Programme, won 1st prize in Gemini (Intermediate) category during the
course's project showcase.
