= Hou Denghao - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Planno

Planno is a desktop address book application targeted to those users who have multiple contacts and events. The users interacts with Planno using a Command Line Interface (CLI) which needs users to type commands instead of clicking buttons. The Graphical User Interface (GUI) of Planno is created with JavaFx. Furthermore, this application is written in Java with 10 thousand lines of code (LOC). With Planno, besides managing contacts and events, users are able to keep track of the participants of their events and collect emails, phone numbers or addresses from the participants of a specific event.The purpose of this portfolio is to highlight the enhancements I have contributed to Planno. Moreover, I will also introduce the other contributions to the development of Planno.

*Code contributed*: [https://github.com/CS2103AUG2017-W14-B4/main/blob/master/collated/main/HouDenghao.md[Functional code]] [https://github.com/CS2103AUG2017-W14-B4/main/blob/master/collated/test/HouDenghao.md[Test code]]

=== Enhancement Added: Sort

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification

Sort command will help users to view a list of sorted persons in the person list according to the alphabetical order of their names. The reason for sorting contacts by their names is because some users may not remember the names of some contacts and it costs them a lot of time to search for a name if they have many contacts. So users may need a command to sort the person list so that they can search for the name like using a dictionary.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sort]

#End of Extract#

---

=== Enhancement Added: Sort Event

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sortE]

#End of Extract#

---

==== Justification

Sort event command will help users to view a list of sorted events in the event list according to the ascending order of their event dates. The reason for sort events by their dates is because it is hard for some users to decide which event to process first. So they may need a command to sort events by their dates and they can choose to process which event first according to the order of events.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sortE]

#End of Extract#

---

=== Enhancement Added: List Event

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=listE]

#End of Extract#

---

==== Justification

List event command will help users to list all the events in the event list. The reason for creating this command is because users will only see some specific events in the event list after they execute some commands. For example, when users type select event command, they can only see the events which a certain person joins. Therefore, users may need a command to view all the events after they filter the event list.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=listE]

#End of Extract#

---

=== Enhancement Added: Show Participants

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=showP]

#End of Extract#

---

==== Justification

Show participants command will help users to show all the participants of a certain event in the person list. The reason for creating this command is because after users execute join command or disjoin command to manage their participants of a certain event, they may want to check their participants and get their contact information. Therefore, users may need a command to view the participants of their events so that they can easily check participants and their contact information.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=showP]

#End of Extract#

---

=== Enhancement Added: FindE

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=findE]

#End of Extract#

---

==== Justification

Find event command will help users to find events whose names contain any of the given keywords and the result will be shown in the event list. The reason for creating this command is because some users may spend a lot of on finding the event they want if the event list is too long. Therefore, users may need a command to find the event quickly by searching its name. Moreover, considering that some users may not remember the full name of the event, find event command only needs some words of the event’s name and it can return the relevant results for users.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=findE]

#End of Extract#

---

=== Other contributions

* Wrote about us and getting started for User Guide(Pull requests https://github.com/CS2103AUG2017-W14-B4/main/pull/52[#52])
* Updated the GUI model and color (Pull requests https://github.com/CS2103AUG2017-W14-B4/main/pull/35[#35], https://github.com/CS2103AUG2017-W14-B4/main/pull/83[#83])
* Reported bugs for the other team's product(Issues https://github.com/CS2103AUG2017-T15-B1/main/issues/102[#102], https://github.com/CS2103AUG2017-T15-B1/main/issues/103[#103], https://github.com/CS2103AUG2017-T15-B1/main/issues/104[#104])
* Wrote additional tests to increase coverage from 74% to 77%(Pull requests https://github.com/CS2103AUG2017-W14-B4/main/pull/152[#152])


