= John Doe - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Find, FindByName, FindByEmail, FindByTag, Mrt, Sort

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=find1]
include::../UserGuide.adoc[tag=find2]
include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification

The search mechanisms are important to the address book as it allows users to find their contacts easily when they have a large amount of contacts.
Moreover, as the schedulers uses the indices to schedule, without this mechanism, the user will have to scroll through large number of the contacts to find the index of the persons they want to schedule.
With this mechanism, the user can search the common features of the people he wants to arrange such that the filtered view consists only of the persons searched and it would be more user friendly.

Sorting the address book also helps the user organise their contacts.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=search]

#End of Extract#

---

=== Enhancement Proposed: Add command `group`



=== Other contributions

* Added the field MRT and valid MRT stations to make finding a meeting place easier (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
