= Lin JiaChao - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: cherBook
cherBook is a desktop application designed to help teachers monitor students' academic performance and manage their schedules.
My team and I built cherBook as an enhancement to the original https://github.com/se-edu/addressbook-level4[`Addressbook-level4`] by https://github.com/se-edu[`Team SE-EDU`].
This project was built as part of the software engineering module `CS2103T` offered by the School of Computing (SoC) in the National University of Singapore (NUS).
The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 30 kLoC.

*Code contributed*: [https://github.com/CS2103AUG2017-T16-B2/main/blob/master/collated/main/lincredibleJC.md[Functional code]] [https://github.com/CS2103AUG2017-T16-B2/main/blob/master/collated/test/lincredibleJC.md[Test code]]

== Roles and Responsibilities
* Role: Team Lead
* Responsibilities:
** In charge of Logic Component.
** Git Expert: Advises the group for git matters.
** Integration: Versioning of the code, maintaining the code repository, integrating various parts of the software to create a whole.
** Scheduling: and tracking: Defining, assigning, and tracking project tasks.

== List of Enhancements Implemented
. Command aliases for all commands
. FindTags Command to find students by Tags
. Statistics Panel Logic and UI

== List of Enhancement Proposed
. Add Compare command to compare statistics of different student groups
. Add SendEmail command to allow sending emails from the command box

---

=== Enhancement Added: Command aliases feature

==== External behavior

Following the list table of shortcuts below, all commands under the `Shorthand` column will behave exactly like the full command in the `Command` column.

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag= commandshortcuts]

#End of Extract#

---

==== Justification

Being a command line application, there is a need to be able to enter commands quickly and without error.
Hence, the usage of shorthand commands for the more verbose full commands are needed.
By adding shorthand commands, the number of key presses needed for the user to execute commands is reduced.
This also reduces the chance of users misspelling commands.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag= commandshortcuts]

#End of Extract#

---

=== Enhancement Added: FindTags feature

==== External behavior

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag= findtags]

#End of Extract#

---

==== Justification

As an address book application, there is a need for users to be able to find their contacts quickly and efficiently .
Since contacts are also categorised by tags, and there was no way to search by tags, I decided to solve this problem by implementing FindTags.

I decided to use AND search and not OR search for FindTags as it narrows down the contact list by their of tags, making it much more efficient to find people with a specific combination of tags.
In this scenario, using OR search for FindTags would not make sense as OR search increases the number of search results as more search terms are used.
Thus making it more difficult and less efficient for the user to find the wanted person.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag= findtags]

#End of Extract#

---

=== Enhancement Added: Statistics Panel feature

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag= statisticspanel ]

#End of Extract#

---

==== Justification

The `StatisticsPanel` is needed to display the statistics of the students currently in the `Students Panel`.
The statistics provided helps teachers monitor their student's academics and identify the weaker students that need more help.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag= statisticspanel ]

#End of Extract#

---

=== Enhancement Proposed: Add command `compare`

==== External behavior
Teh user can enter the `compare` command followed by 2 `Tags` or `FormClassNames` to compare statistics of different groups with the compare command.
The `Statistics Panel` will have a second set of values for the second group of students.

The difference in the 2 sets of values will be displayed on the right of the `StatisticsPanel`.
The difference will be colored [red]#red# if the difference is negative and [green]#geen# if the difference is positive to to make it noticeable and more visually appealing.


==== Justification
Teachers often have to compare the grades of students or groups of students to analyse their academic progress.
As the simple statistics can only tell you so much about your data, there is a need for more powerful data analytics.
The `comapre` command gives teachers a more powerful tool to analyse data by allowing them to compare different sets of data .
The color coded difference values also improve the readability of the statistics so that teachers can get a good idea of the relative performance of two groups of students at a glance.

---

=== Enhancement Proposed: Add command `sendemail`

==== External behavior
The user can enter the `sendemail` command followed by the `INDEX` of the intended recepient and an external email application with the _FROM_ and _TO_ fields already populated.
This streamlines the process of teachers sending emails to students and parents and allows them to do it directly from  within cherBook.

==== Justification
It is troublesome for teachers to manually and repeatedly open up their browsers to send emails to students of their parents.
The `sendemail` command removes this process and streamlines the process by bringing the teacher straight to the compose email page with the relevant fields already filled, removing the trouble of going through a browser.

---

=== Other contributions

* Added Travis, AppVeyor and Coveralls on the cherBook repository automated deployment and testing. (Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/7[#7], https://github.com/CS2103AUG2017-T16-B2/main/pull/152[#152])
* Added Grades and FormClass attributes to the Student (Pull Requests https://github.com/CS2103AUG2017-T16-B2/main/pull/39[#39], https://github.com/CS2103AUG2017-T16-B2/main/pull/41[#41])
* Populated cherBook with a significant amount (40 student contacts) of realistic data (Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/73[#73])
* Cleaned up unnecessary nesting in the ExtendedPersonCard UI element (Commit https://github.com/CS2103AUG2017-T16-B2/main/pull/98/commits/1a6bc459dc455d4e776e48586856734bb7574eba[1a6bc45] in Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/98[#98])
* Cleaned up code smells in the whole repository (Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/123[#123])

=== Helping out other groups

* Performed acceptance testing for other teams, reported bugs and gave suggestions
** CS2103AUG2017-T09-B3 (Issues https://github.com/CS2103AUG2017-T09-B3/main/issues/150[#150], https://github.com/CS2103AUG2017-T09-B3/main/issues/151[#151], https://github.com/CS2103AUG2017-T09-B3/main/issues/152[#152], https://github.com/CS2103AUG2017-T09-B3/main/issues/153[#153])
** CS2103AUG2017-T11-B1 (Issues https://github.com/CS2103AUG2017-T11-B1/main/issues/136[#136], https://github.com/CS2103AUG2017-T11-B1/main/issues/137[#137])

== Project: NUShortcuts

https://nushortcuts.herokuapp.com/[`NUShortcuts`] is a web application to provide walking shortcuts around NUS with step by step picture guides .
This was done from May 2017 to Aug 2017 for `CP2106` - Orbital Programme  offered by the School of Computing (SoC) in the National University of Singapore (NUS).
This web application was built using the `MeteorJS` framework and is deployed on a `Heroku` server.

https://nushortcuts.herokuapp.com/[`NUShortcuts`] offers three route types: Fastest route, Sheltered route and Least Stairs route.
Users can search for their destination in NUS, choose their desired path and follow the picture guides to their destination.
For better travel time estimates, they can indicate their mode of transport and their estimated walking speeds under the settings page.
My team also implemented a ranking system to track the most popular and frequently searched locations.
One of the biggest features I implemented was the algorithm behind the calculation of the shortest paths around NUS.
Some of the other features I implemented include the feedback page where users can give feedback on how to improve NUShortcuts.
