= Lin JiaChao - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: cherBook
cherBook is an address book application used by teachers to monitor students' academic progress.
The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 8 kLoC.

*Code contributed*: [https://github.com/CS2103AUG2017-T16-B2/main/blob/master/collated/main/lincredibleJC.md[Functional code]] [https://github.com/CS2103AUG2017-T16-B2/main/blob/master/collated/test/lincredibleJC.md[Test code]]

== Roles and Responsibilities
* Role: Team Lead
* Responsibilities:
** In charge of Logic Component
** Git Expert: Advises the group for git matters.
** Integration: Versioning of the code, maintaining the code repository, integrating various parts of the software to create a whole.
** Scheduling: and tracking: Defining, assigning, and tracking project tasks.

== List of Enhancements Implemented
. Add Command aliases for all commands
. Add Grades and FormClass attributes to the Student
. Add FindTags Feature to find students by Tags
. Add Statistics Panel

== List of Enhancement Proposed
. Add Compare command to compare statistics of different student groups
. Add SendEmail command to allow sending emails from the command box

---

=== Enhancement Added: Add Command aliases for all commands

==== External behavior

Following the list table of shortcuts below, all commands under the `Shorthand` column will behave exactly like the full full command in the `Command` column.

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag= commandshortcuts]

#End of Extract#

---

==== Justification

Being a command line application, there is a need to be able to enter commands quickly and without error.
Hence, the usage of shorthand commands for the more verbose full commands are needed.
By adding shorthand commands, it reduces the number of key presses needed for the user to execute commands.
This also helps reduce the probability of misspelling commands by users who are not touch typists.

==== Implementation

---
#Start of Extract [from: Developer Guide]#
//TODO: write up for developer guide
//include::../DeveloperGuide.adoc[tag= commandshortcuts]

#End of Extract#

---

=== Enhancement Added: Add Grades and FormClass attributes to the Student

==== External behavior

---
#Start of Extract [from: User Guide]#
//TODO: write up for user guide
//include::../UserGuide.adoc[tag= ]

#End of Extract#

---

==== Justification

One of the main features cherBook has is calculating statistics for a list of students, and the Grades attribute is needed for it.
Similarly, with comparing the statistics of different classes as a upcoming feature, the FormClass attribute is also needed.

==== Implementation

---

#Start of Extract [from: Developer Guide]#
//TODO: write up for developer guide
//include::../DeveloperGuide.adoc[tag= ]

#End of Extract#

---

=== Enhancement Added: FindTags

==== External behavior

---

#Start of Extract [from: User Guide]#
include::../UserGuide.adoc[tag= findtags]
#End of Extract#

---

==== Justification

As an address book application, there is a need for users to be able to find their contacts quickly and efficiently .
Since contacts are also categorised by tags, and there was no way to search by tags, I decided to solve this problem by implementing FindTags.

I decided to use AND search and not OR search for FindTags as it narrows down the contact list by their of tags, making it much more efficient to find people with a specific combination of tags.
In this scenario, using OR search for FindTags would not make sense as OR search increases the number of search results as more search terms are used.
Thus making it more difficult and less efficient for the user to find the wanted person.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag= findtags]

#End of Extract#

---

=== Enhancement Added: Statistics Panel

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag= statisticspanel ]

#End of Extract#

---

==== Justification

This panel is needed to display the statistics of the students currently in the Students Panel.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag= statisticspanel ]

#End of Extract#

---

=== Enhancement Proposed: Add command `compare`

==== External behavior
Enter the `compare` command followed by 2 `Tags` or `FormClassNames` to compare statistics of different groups with the compare command.
The Statistics Panel will have a second set of values for the second group of students.

To make the difference more noticeable, the difference in the 2 sets of values will be displayed on the right-hand side.
The difference will be colored red if the difference is negative and green if the difference is positive to to make it more visually appealing.


==== Justification
Teachers often have to compare the grades of students or groups of students to analyse their academic progress.
As the simple statistics can only tell you so much about your data, there is a need for more powerful data analytics.
The `comapre` command gives teachers a more powerful tool to analyse data by allowing them to compare different sets of data .
The color coded difference values also improve the readability of the statistics so that teachers can get a good idea of the relative performance of two groups of students at a glance.

==== Implementation

=== Enhancement Proposed: Add command `SendEmail`

==== External behavior
Enter the `sendemail` command followed by the index of the intended recepient and an external email application with the FROM and TO fields already populated.
This streamlines the process of teachers sending emails to students and parents and allows them to do it directly from  within cherBook

==== Justification
It is troublesome for teachers to manually and repeatedly open up their browsers to send emails to students of their parents.
The `sendemail` command removes this process and streamlines the process by bringing the teacher straight to the compose email page with the relevant fields already filled, removing the trouble of going through a browser.

==== Implementation

=== Other contributions

* Set up Travis and Coveralls and updated Badges for the Team Repository ( Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/7[#7] )
* Populated cherBook with a significant amount (40 student contacts) of realistic data ( Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/73[#73] )
* Cleaned up unnecessary nesting in the ExtendedPersonCard UI element ( Commit https://github.com/CS2103AUG2017-T16-B2/main/pull/98/commits/1a6bc459dc455d4e776e48586856734bb7574eba[1a6bc45] in Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/98[#98])
* Cleaning up of code in the whole repository ( Pull Request https://github.com/CS2103AUG2017-T16-B2/main/pull/123[#123] )

=== Helping out other groups

* Found Bugs and gave Suggestions to other groups as acceptance testing.
** CS2103AUG2017-T09-B3 (Issues https://github.com/CS2103AUG2017-T09-B3/main/issues/150[#150], https://github.com/CS2103AUG2017-T09-B3/main/issues/151[#151], https://github.com/CS2103AUG2017-T09-B3/main/issues/152[#152], https://github.com/CS2103AUG2017-T09-B3/main/issues/153[#153])
** CS2103AUG2017-T11-B1 (Issues https://github.com/CS2103AUG2017-T11-B1/main/issues/136[#136], https://github.com/CS2103AUG2017-T11-B1/main/issues/137[#137] )


== Project: NUShortcuts

https://nushortcuts.herokuapp.com/[NUShortcuts] is a web application to provide step by step picture guides to for shortcuts around NUS.
This was done for CP2106 - Orbital Programme from May 2017 to Aug 2017. Over the three months, I have implemented all three route types:
Fastest Route, Sheltered route and Least Stairs. Users can search for their desired locations in NUS, check its details and see the shortest walking path and route by bus to the destination.
Through the settings menu, users can also customise their choice of transport and their estimated walking speed to get better estimates.
I also implemented a Ranking system for the most commonly travelled locations and also a feedback page where users can give feedback on how to improve the application.
