= Jolyn Tan - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

ifdef::env-github[]
https://cs2103aug2017-w11-b2.github.io/main/team/Jolyn.html[Please click here to view portfolio.]
endif::[]

ifndef::env-github[]
== Project: Rolodex

include::../../README.adoc[tag=applicationDescription]

*Code contributed*: [https://github.com/CS2103AUG2017-W11-B2/main/blob/master/collated/main/jo-lyn.md[Functional code]] [https://github.com/CS2103AUG2017-W11-B2/main/blob/master/collated/test/jo-lyn.md[Test code]]

=== Enhancement Added: Keyboard Shortcuts

The table below shows the keyboard shortcuts that are added, with the exception of shortcuts with the behavior `Exit the application`
and `View help window` which came with the original state of the application.

==== External Behavior

---

include::../UserGuide.adoc[leveloffset=2,tag=shortcut]

---

==== Justification

The main objective of Rolodex is to facilitate an efficient way of managing contacts for users with a preference for typing.
Having keyboard shortcuts allows the user to navigate around the application with ease and speed.
This implementation should enable the user to access all parts of the application without using the mouse.

==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=2, tag=shortcut]

---

=== Enhancement Added: UI Improvements

---

include::../DeveloperGuide.adoc[leveloffset=1, tag=uiImprovements]

---

[[detailPanel]]
=== Enhancement Added: Person Detail Panel

==== External Behavior

---

include::../DeveloperGuide.adoc[leveloffset=1, tag=detailPanelBehavior]


==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=1, tag=detailPanelImp]

---

=== Enhancement Added: Remark Field

The remark field allows the user to store miscellaneous notes about their contacts. The field can be added using a standalone `remark` command,
or added along with other fields when adding a new person using the existing `add` command. Similarly, the field can be modified with the `remark` command,
or edited along with other fields using the existing `edit` command.

==== External Behavior

---

include::../UserGuide.adoc[leveloffset=2,tag=remark]

---


=== Enhancement Proposed: Add Profile Pictures

==== External Behavior

---

include::../UserGuide.adoc[leveloffset=2, tag=picture]

---
=== Other contributions
* Imported the Segoe UI font pack into the application (Pull request https://github.com/CS2103AUG2017-W11-B2/main/pull/136[#136])
* Added a prompt text to the result display panel (Pull request https://github.com/CS2103AUG2017-W11-B2/main/pull/122[#122])
* Added the removeTag method (Pull request https://github.com/CS2103AUG2017-W11-B2/main/pull/6[#6])
* Updated the General Documentation (Pull requests https://github.com/CS2103AUG2017-W11-B2/main/pull/2[#2],
https://github.com/CS2103AUG2017-W11-B2/main/pull/66[#66],
https://github.com/CS2103AUG2017-W11-B2/main/pull/112[#112],
https://github.com/CS2103AUG2017-W11-B2/main/pull/124[#124],
https://github.com/CS2103AUG2017-W11-B2/main/pull/134[#134])

endif::[]

ifndef::env-github[]
include::../NavigationMenu.adoc[]
endif::[]
