= Lim KangJie Jonathan - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: cherBook
 cherBook is an address book application used by teachers to monitor students' academic progress.
 The user interacts with it using a CLI, and it has a GUI created with JavaFX.
 It is written in Java, and has about 30 kLoC.

=== Enhancement Added: Remark

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=remark]

#End of Extract#

---

==== Justification

We added remark such that the user can record the progress of students that can be easily known at a glance.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=remark]

#End of Extract#

---
=== Enhancement Added: GraphPanel

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=graphpanel]

#End of Extract#

---

==== Justification

To display the results of all students in the same class to see the difference in grades that can be seen at a glance.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=graphpanel]

#End of Extract#

---
=== Enhancement Added: Tab

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tab]

#End of Extract#

---

==== Justification

To display different representations of graphs as some are more appropriate in different scenarios.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tab]

#End of Extract#

---
=== Enhancement Added: Home

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=home]

include::../UserGuide.adoc[tag=homepanel]
#End of Extract#

---

==== Justification

Added a home page to help lift one's mood when using the application.
In addition, it can act as a soft security measure when a teacher needs to leave the desk and in doing so prevents
leak of information from passer bys.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=home]

#End of Extract#

---
=== Enhancement Proposed: Add 25 & 75 percentile lines
==== External Behaviour
No external behaviour, when the statistics panel calculates the results, the line would be drawn at the different percentiles on the line graph.

==== Justification
Helps the teacher to easily show who are the students who are over and under performing and can easily use the graph for their reports.

==== Implementation
Create a line on the graph which would by sync to the figures provided by the statistics panel, such that every time the list changes,
so does the line.

=== Enhancement Proposed: Refresh Home panel wallpaper
==== External Behaviour
Changes the wallpaper every time the home command is typed or when the application starts up.

==== Justification
Adds more variety to their wallpaper so that they do not have to feel bored looking at the same photo

==== Implementation
Read the filepath of the folder of wallpapers and creating a new array of files. Randomly pick a file and set it to Image every time the home
command is entered.

=== Other contributions

* Updated the GUI to include graphs of students either in class or tags (pull request https://github.com[#65], https://github.com[#87])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
* Logic tabCommand implementation (Special thanks to Celine who helped me layout tabCommand) (https://github.com/CS2103AUG2017-T16-B2/main/pull/114)
* Update Manual Testing Script (https://github.com/CS2103AUG2017-T16-B2/main/pull/146)
* Rearranged panels in FXML such that Student Details Panel, Statistics Panel and Graph Panel are all on the same stack pane. (https://github.com/CS2103AUG2017-T16-B2/main/pull/139/files)
* Fixed some bugs issues regarding help window (https://github.com/CS2103AUG2017-T16-B2/main/pull/157)

== Project: Tea (Game)

A unity made 2D side scroller game that focuses on interacting with the surrounding environment to survive as long as possible.
Some features include a combat system with wild animals, materials collected to create vase to collect water, wood chopped from
trees to start fire etc. Some other features are event system where choices are given and there would be penalties (reduction
of health, etc) or boons (receiving more food). Weapons and shelter can be crafted to aid in survival as well.


