= Joshua Lim - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: ConnectUs
ConnectUs is a desktop address book application used to store contact information such as name, phone, email and address. 
The user can tag entries for more efficient search and can open up an email client to send an email. The GUI displays the list of contacts as well as additional information
such as his/her address on Google Maps. The user interacts with it using a CLI, although there are additional GUI elements created in JavaFX such as a form to edit contacts, and a QR generator for you to scan
the contact's number and automatically port it to your smartphone. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Undo/Redo

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=email]
include::../UserGuide.adoc[tag=googlemaps]
include::../UserGuide.adoc[tag=mapbutton]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=joshua]

#End of Extract#

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* In-charge of weekly milestone allocation and scheduling
* Assisted Jasmine in her upload photo feature, suggested her to save each image with a unique ID (email)
* Assisted Daniel in designing and Mapping his QR Code feature

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
