= Ken Lim Tien Tze - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Personal Information Management Program (PIMP)
Personal Information Manager Program (PIMP) is a command line interface (CLI) address book that allows you to store your contacts. You can use PIMP to add friends, add specific tags to them, add their social media accounts (such as Facebook, Twitter, Instagram), or add remarks. You can search through the list of your contacts by typing specific names. For more advanced user, you can use regex to find your friends. Most of the functionality works by typing in single line commands. It is written in Java.

*Code contributed*: [https://github.com/CS2103AUG2017-W10-B1/main/blob/master/collated/main/kenpaxtonlim.md[Functional code]] [https://github.com/CS2103AUG2017-W10-B1/main/blob/master/collated/test/kenpaxtonlim.md[Test code]]

=== Enhancement Added: Quickhelp

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=quickhelp]

#End of Extract#

---

==== Justification

For new users, it can be quite difficult to remember all the commands. Typing in the `HelpCommand` will bring up the help window which may be quite a hassle to do it all the time. The `QuickhelpCommand` allows the user to quickly view all the valid command words that can be used, saving time.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=quickhelp]

#End of Extract#

---

=== Enhancement Added: Add/Remove Tags

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=addremovetags]

#End of Extract#

---

==== Justification

For existing `EditCommand`, editing tags replaces the entire set of tags with the ones keyed in by user. To makes adding or removing a few tags simplier, this command is added to add or remove tags from the existing set without completely replacing it.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=addremovetags]

#End of Extract#

---

=== Enhancement Added: Social Media

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=socialmedia]

#End of Extract#

---

==== Justification

As the target user is a socialite, he/she will be very involved in social media. As such, having access to the social media pages directly from PIMP will be ideal.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=socialmedia]

#End of Extract#

---

=== Enhancement Added: Sort

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification

Just like any contact list app, the list should be sorted so that it is easier for the user to view. With natural ordering, the list also looks neater.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sort]

#End of Extract#

---

=== Other contributions

NIL
