= Khor Shao Liang - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Add multiple persons from `.txt` file

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=multiple]

#End of Extract#

---

==== Justification

Adding multiple persons will aid users (e.g. tutors) who need to add multiple persons, and it would be too tedious to add them one by one. With the new feature implemented it would improve such users convenience in using the software.

== Project: GoPost!

GoPost! is an exciting platform that provide users a one-stop portal for all events needs. The web application offers a spectrum of features and utility. Users will be able to create events, create a registration forms, manage their events schedules, and many more.
