= Khor Shao Liang - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com/KhorSL/main[Functional code]] [https://github.com/KhorSL/main[Test code]]

=== Enhancement Added: Add multiple persons from `.txt` file

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=multiple]

#End of Extract#

---

==== Justification

Adding multiple persons will aid users (e.g. tutors) who need to add multiple persons,
and it would be too tedious to add them one by one.
With the new feature implemented it would improve such users convenience in using the software.

=== Enhancement Added: Find persons by name, tags and email

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=find]

#End of Extract#

---

==== Justification

Allowing users to find persons based on tags will allow users to know the relationship with their contact.

=== Enhancement Added: Merge given XML file to default storage XML file

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=merge]

#End of Extract#

---

==== Justification

Main tutors with many assistant tutors is able to merge the different address book of my assistant tutors
so as to have all the student contacts.

== Project: GoPost!

GoPost! is an exciting platform that provide users a one-stop portal for all events needs. The web application offers a spectrum of features and utility. Users will be able to create events, create a registration forms, manage their events schedules, and many more.
