= Ng Kheng Yi - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Schedubook
Schedubook is a desktop address book application which acts as both an address book and also acts as an aide for
the scheduling of meetings, catering mainly to students. In addition to storing contacts and the information of
meetings, Schedubook is also able to remind its users of upcoming meetings through the use of a popup and colours to
indicate the urgency of certain meetings. The user interacts with it using a CLI, and it has a GUI created with JavaFX.

The purpose of this portfolio is to showcase the contributions that I have made towards the building of this
application and also to justify the addition of the features or enhancements that I have made to the application.

//*Code contributed*: [link:../../collated/kyngyi.md[Main code]] [https://github.com[Test code]]


=== Enhancement Added: Edit Meeting


==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=editmeeting]

#End of Extract#

---

==== Justification

Addition of the `editmeeting` command allows the changing of details a `Meeting` object created by the user when required. For
example the location of a set meeting might be changed after the creation of the meeting and hence the `editmeeting` command would
be required to reflect this change in ScheduBook.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=editmeeting]

#End of Extract#

---

=== Enhancement Added: Find Exact Meeting


==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=findexactmeeting]

#End of Extract#

---

==== Justification

The implementation of `findexactmeeting` allows users to narrow down their search results as compared
to when using the `findmeeting` command as the conditions for a meeting to match the search results
are more strict. This command is useful when dealing with a large amount of meetings in the meeting list with people
of similar names. _e.g, Clara Tan and Clara Soh_

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=findexactmeeting]

#End of Extract#

---

=== Enhancement Proposed
* Integration of Google Calendar(Allowing import and export of meetings)
* Notifcation of meetings even when application is closed

=== Other contributions

* Updated undo command to apply to commands related to Meetings (Pull request https://github.com/CS2103AUG2017-T09-B2/main/commit/4dc2249ca6c45d4c4f104cc649226f14673d7379[#63])
* Modified delete command to delete Meetings with deleted person (Pull request https://github.com/CS2103AUG2017-T09-B2/main/commit/b9db535b31628dca385586b6d69454aeb5d805be[#109])
