= Lim Yong Song - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: The Classroom
The Classroom is a desktop application that helps users manage their contacts and keep track of tasks or remarks that pertain to specific contacts.
It is especially helpful in helping students manage and increase the efficiency of their group work. +
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 8 kLoC. +
The Classroom is built up from the [https://github.com/se-edu/addressbook-level4[AddressBook - Level 4]] (an address book application used for teaching Software Engineering principles)

*Code contributed*: [https://github.com/CS2103AUG2017-T09-B4/main/blob/master/collated/main/limyongsong.md[Functional code]] [https://github.com/CS2103AUG2017-T09-B4/main/blob/master/collated/test/limyongsong.md[Test code]]

=== Enhancement Added: Remark CheckList 
Allow user to add and remove specific remarks pertaining to any persons in the contact

==== External behaviour

---
#Start of Extract [from: User Guide]#

include::..\UserGuide.adoc[tag=remarkchecklist]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::..\DeveloperGuide.adoc[tag=remarkchecklist]

#End of Extract#

---

=== Enhancement Proposed:

//{Explain similar to the Undo/Redo feature above.}

=== Other contributions

//* Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
//* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project:

{Optionally (not graded), you may include other projects in your portfolio.}
