= Melvin Leo - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: ScheduBook
_ScheduBook_ is a desktop address book application that can be used by students or businessmen to better manage their schedules with their peers or acquaintances. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java and currently has about 9 kLoC. +
 +
This project is a product of Software Engineering, CS2103T in NUS. _ScheduBook_ is proudly developed by my team based on https://github.com/se-edu/addressbook-level4[AddressBook(Level4)], by https://se-edu.github.io/[SE-EDU] team, initial address book application created to be used for teaching Software Engineering principles. Through this project, I gained insights on the work environment of software engineers and experienced how software engineers approach and contribute to a certain software development.

== Purpose

This project portfolio provides the contributions of Melvin Leo towards this project. Furthermore, it provide insights of the implementation of certain features that Melvin implemented in _ScheduBook_.

*Code contributed*: [https://github.com/CS2103AUG2017-T09-B2/main/blob/master/collated/main/Melvin-leo.md[Functional code]] [https://github.com/CS2103AUG2017-T09-B2/main/blob/master/collated/test/Melvin-leo.md[Test code]]

=== Enhancement Added: Meeting Class

==== External behavior

---


include::../UserGuide.adoc[tag=meetingCard]


---

==== Justification

For the ease of the user, the meeting cards are positioned and presented in such a way that the user can retrieve the information he/she wants immediately without much effort. The meeting cards are also sorted in chronological order so that the user can see the meetings that have higher urgency. Furthermore, the colours are also implemented for the user to keep track of his/her upcoming meetings. The name and the phone number of the person who the user will be meeting are shown so that if needed, the user can contact that person with ease.

==== Implementation

---

include::../DeveloperGuide.adoc[tag=meetingClass]

include::../DeveloperGuide.adoc[tag=meetingCard]

---

=== Enhancement Added: Reminder Pop up

==== External behavior

---


include::../UserGuide.adoc[tag=popUp]


---

==== Justification

This implementation further boosts our capability of reminding of _ScheduBook_. After implementing the meeting cards, we realised that despite the coloured card, there was no significant reminder that can really catch the eye of the users. However, this pop-up reminder is significant to a large extent and most of the details are shown to the user. Furthermore, the user will have to acknowledge the pop up before actually entering the application.

==== Implementation

---

include::../DeveloperGuide.adoc[tag=meetingPopup]


---

=== Enhancement Added: Automatic deletion of past meetings

==== External behavior

---


include::../UserGuide.adoc[tag=autodelete]


---

==== Justification

In order for _ScheduBook_ to be more user-friendly and convenient, automatic deletion of meetings that have past the scheduled date and time should be implemented, since there is no need for the application to remind the user of an overdue meeting.

==== Implementation

---

include::../DeveloperGuide.adoc[tag=autoDelete]


---

=== Enhancement Proposed: Search command by tags
This allows user to search contact list by tags. Hence, finding person will be easier.

=== Enhancement Proposed: Import/export Google Contacts
To better integrate _ScheduBook_ into our users' lives, _ScheduBook_ will be implementing the ability to import google contacts so that users can easily sync their own contact list to _ScheduBook_. Scheduling meeting with his/her contacts will be much more convenient.

=== Enhancement Proposed: A pop-up for clashing meeting
A pop-up reminder will be opened when user adds a meeting that is within fifteen minutes of another meeting. It is just to remind the user so that he/she will be aware that there is another meeting that are near and to make changes if necessary.

=== Other contributions

Contribution to _ScheduBook_

* Added Meeting Tags for meeting cards to indicate importance of meeting. (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/191[#191])
* Added Junit Test cases (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/148[#148], https://github.com/CS2103AUG2017-T09-B2/main/pull/141[#141], https://github.com/CS2103AUG2017-T09-B2/main/pull/202[#202], https://github.com/CS2103AUG2017-T09-B2/main/pull/214[#214])
* Updated UI of Meeting List (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/54[#54], https://github.com/CS2103AUG2017-T09-B2/main/pull/77[#77])
* Solved UI of background colour problem (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/200[#200])
* Created valid date regex to solve leap year bug (Pull request https://github.com/CS2103AUG2017-T09-B2/main/pull/187[#187])
* Added Coverall for whole project repo (https://coveralls.io/github/CS2103AUG2017-T09-B2/main[Coverall])


== Project: FPGA audio Fx (Verilog programming for EE2020 in NUS)
