= Nelson Quek Yee Jiel - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: ScheduBook
_ScheduBook_ a desktop address book application intended for students to plan and schedule their meetings with their peers, tutors or professors. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 9 kLoC(Lines of Code).

This project is a product of the module, Software Engineering, CS2103T, in NUS. _ScheduBook_ is proudly developed by my team based on https://github.com/se-edu/addressbook-level4[AddressBook(Level4)], and by https://se-edu.github.io/[SE-EDU] team, whose initial address book application was created to be used for teaching Software Engineering principles.


*Code contributed*: [https://github.com/CS2103AUG2017-T09-B2/main/blob/master/collated/main/nelsonqyj.md[Functional code]] [https://github.com/CS2103AUG2017-T09-B2/main/blob/master/collated/test/nelsonqyj.md[Test code]] {give links to collated code files}

=== Enhancement Added: AddMeeting, SelectMeeting, GoogleMaps

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=addmeeting]

include::../UserGuide.adoc[tag=selectmeeting]

include::../UserGuide.adoc[tag=googlemaps]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

There is a need for users, especially students, to properly plan their important meetings. Thus, the addmeeting feature is implemented to allow users
to create meetings with existing contacts and to be reminded of the meeting when it is due. Furthermore, by using the
selectmeeting command, the location of the meeting will be automatically loaded into Google Maps as the destination and all the user
needs to do is just to input their current location and the directions to the meeting location will be shown. This allows the
user to properly plan their time needed and route to meeting locations.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=addmeeting]

include::../DeveloperGuide.adoc[tag=selectmeeting]

#End of Extract#

---

=== Enhancement Proposed: Add follow-up meetings

Allows user to continue to add on from the original meeting which keeps track and archive the previous meeting details
such as location and meeting partners.

=== Other contributions

* Updated the GUI color scheme (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/103, https://github.com/CS2103AUG2017-T09-B2/main/pull/110)
* Wrote additional tests to improve coverage (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/125, https://github.com/CS2103AUG2017-T09-B2/main/pull/127)

== Project: FPGA Design Project: Real-Time Audio Effects (Verilog Programming in Digital Fundamentals EE2020)

