= Khor Ru Shan - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets
:collatedDir: ../../collated

== Project: MedNus
MedNus is a desktop address book application used by Medical Professionals. +
The user interacts with it using a CLI, and it has a GUI created with JavaFX. +
It is written in Java, and has about 10 kLoC.

*Code contributed*: +
link:{collatedDir}/main/rushan-khor.md[Functional code] +
link:{collatedDir}/test/rushan-khor.md[Test code]

=== Enhancement Added: Batch deletion of contacts by tag

==== External behaviour

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=batch]

#End of Extract#

---

==== Justification

Batch deletions make it less tedious to perform deletions on multiple contacts.

---

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=batch]

#End of Extract#

---

=== Enhancement Added: Display potential duplicate contacts

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=dups]

#End of Extract#

---

==== Justification

Duplicate contacts can accumulate over time. The `duplicates` command compiles a list of potential duplicate contacts for the user to review.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=dups]

#End of Extract#

---

=== Enhancement Added: Copy contact email address to clipboard

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=copy]

#End of Extract#

---

==== Justification

Embracing the keyboard-centric interaction of MedNus, even copying data into the user’s clipboard is possible using purely keyboard commands. The Copy command lets users do just that.

---

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=copy]

#End of Extract#

---

=== Enhancement Proposed

* Skype username field and ability to pull contacts from Skype
** This is useful for telemedicine / telehealth which is essentially remote doctor consulting facilitated by video-calls
** This would further solidify MedNus's relevance as a forward-looking product for medical professionals
* Command that maps (patient contacts) with (doctor contacts specialising in their illness) and drafts referral letters for them
** This is useful for private doctors in particular, for whom networks of referrals are poorly documented, yet crucial to their business

=== Other contributions

* Drafted a light UI theme
* Revamped the Developer Guide content with Eric
