= *Sebastian Tay - Project Portfolio*
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images

== *Project: Sales Navigator*
Sales Navigator is a desktop address book application used for sales executives to keep track of their connections and contacts.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 16 kLoC.

*Code contributed*: https://github.com/CS2103AUG2017-T14-B3/main/blob/master/collated/main/sebtsh.md[Functional code]
https://github.com/CS2103AUG2017-T14-B3/main/blob/master/collated/test/sebtsh.md[Test code]

=== *Enhancement added: Additional optional parameters - Company, Position, Priority, Status, Note*
==== *External behaviour*

---
Start of Extract [from: User Guide]

include::../UserGuide.adoc[lines=64..78;85..109]
End of Extract

---
==== *Justification*
Company, Position, Priority, Status and Note are left as optional fields as not everybody in the sales executive's address book
may be their business contacts (e.g. friends, family) and hence not every contact will need these. They are thus initialized
to a NIL value if not explicitly initialized by the user.

==== *Implementation*

---
Start of Extract [from: Developer Guide]

include::../DeveloperGuide.adoc[lines=478..547]

End of Extract

---
=== *Enhancement added: Automatic update of Person card and Person panel details when edits are made*
==== *External behaviour*
Person panel details, as well as Person card priority label and colour, are automatically updated when the
user makes edits to them.

==== *Justification*
The user will be confused if he edits a field but the change is not reflected in the UI immediately.

==== *Implementation*

---
Start of Extract [from: Developer Guide]

include::../DeveloperGuide.adoc[tag=autoupdate]

End of Extract

---

=== *Enhancement proposed: Add commands `google`, `facebook`, `instagram`*
==== *External behaviour*
Users will be able to Google, Facebook, Instagram search the people in their address book. For example, the command
[google 1] will load a browser displaying a Google search of that person's name. Similar commands apply for
Google and Instagram respectively.

==== *Justification*
Users may want to find out more information about the people in their address book. Implementing such a feature
would make this more convenient for them, instead of opening another browser and typing in the name.

==== *Implementation*
This would be implemented by adding the new commands into the Logic component. Upon executing these commands, their
default external browser (e.g. Chrome, Firefox) would be opened with the search results of the name.

==== *Design Considerations*:
*Aspect*: Implementation of browser loading

*Alternative 1 (current choice)*: Load the search results in the user's default external browser

*Pros*: User will be able to use their session logins (e.g. their Facebook, Instagram accounts) with the results.
Also, the browser will be bigger for them to use instead of in the small window. More natural for them to browse the
web with their default browsers.

*Cons*: Users may not want their default browsers open. Will take time to load browsers. Users have to switch between
apps

*Alternative 2 (current choice)*: Load the search results in the BrowserPanel in the main panel of the app

*Pros*: Users can see the search results without having to leave the app.

*Cons*: The small main panel of the app is not conducive for web browsing. Users do not have their session logins
within the app and have to login again.

=== *Other contributions*

* UI design (PersonPanel, EventPanel) (Pull requests #41, #56)
* UI enhancements (deselection when moving from person selection to event selection and vice versa) (Pull request #59)
* In charge of team repo (coordinate PRs, merge PRs, ensure team repo passes Travis CI checks at all times, collate)
