= Tao Jiashu - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: UniCity
UniCity is a desktop address book application used to help university students manage their ever-growing network.
The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 16 kLoC (16 000 Lines of Code).

=== Enhancement Added: Favourite

==== External behavior

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=favourite]

#End of Extract#

---

==== Justification

Favourite has become a standard function in all modern address book applications across all platforms.
The reason behind this is that users want to differentiate some of their favourite contacts from the others. Therefore, `FavouriteCommand` is implemented in UniCity so that users will not miss this function when first switching to UniCity.

==== Implementation

---

#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=favourite]

#End of Extract#

---

=== Enhancement Added: ShowFavourite

==== External behaviour

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=showfavourite]

#End of Extract#

---

==== Justification

This feature is added to complement `FavouriteCommand`.
After being able to mark some persons in UniCity as favourite, users naturally want to keep track of all the favourite
contacts after some time. Therefore, this functionality is introduced to UniCity.

==== Implementation

The command will go through the entire current contact list. If a person is a favourite contact, it will be updated to
FilterPersonList of the model. This list will be displayed after all persons in the current list are checked.

=== Enhancement Added: Locate

==== External behaviour

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=locate]

#End of Extract#

---

==== Justification

Sometimes, users have no idea where the address of some people are. Thus, it will be very help to integrate Google Maps to UniCity so that users can locate their contacts' home address easily.

==== Implementation

Similar to `SelectCommand`, `LocateCommand` will raise an event to the event centre. The event will store the address of the selected person as its field.
Then when loading the Google Maps search page, the address will be added to the Google Maps prefix.

=== Enhancement Proposed: Add command `AddMemory`

==== Justification

This feature will definitely make our product stand out from other address book applications. With this feature, users will be able to add their unique memories with their contacts,
so that they can look back at their memorable moments with certain persons if you want to. They would also be reminded who that person is if they ever forgot who that person is.

=== Other contributions

* Fixed a few bugs so that Travis can run properly (Pull requests https://github.com/CS2103AUG2017-W13-B1/main/pull/13[#13], https://github.com/CS2103AUG2017-W13-B1/main/pull/23[#23], https://github.com/CS2103AUG2017-W13-B1/main/pull/90[#90])

=== Collated Code
https://github.com/CS2103AUG2017-W13-B1/main/blob/master/collated/main/taojiashu.md[Click to see]