= Tao Jiashu - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: UniCity
UniCity is a desktop address book application used to help university students manage their ever-growing network.
The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 16 kLoC (16 000 Lines of Code).

=== Enhancement Added: Favourite

==== External behavior

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=favourite]

#End of Extract#

---

==== Justification

Favourite has become a standard function in all modern address book applications across all platforms.
The reason behind this is that users want to differentiate some of their favourite contacts from the others. Therefore, `FavouriteCommand` is implemented in UniCity so that users will not miss this function when first switching to UniCity.

==== Implementation

---

#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=favourite]

#End of Extract#

---

=== Enhancement Added: ShowFavourite

==== External behaviour

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=showfavourite]

#End of Extract#

---

==== Justification

This feature is added to complement `FavouriteCommand`.
After being able to mark some persons in UniCity as favourite, users naturally want to keep track of all the favourite
contacts after some time. Therefore, this functionality is introduced to UniCity.

==== Implementation



=== Enhancement Added: Locate

==== External behaviour

---

#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=locate]

#End of Extract#

---

==== Justification

Sometimes, users have no idea where the address of some people are. Thus, it will be very help to integrate Google Maps to UniCity so that users can locate their contacts' home address easily.

==== Implementation



=== Enhancement Proposed:


=== Other contributions

* Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}