= TravisPhey - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: TheYellowPage
TheYellowPage is a desktop address book application designed with the needs of office workers in mind. The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX. It is written in Java, and has about 6000 lines of code.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== 1st Enhancement Added: DeleteMultipleCommand

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=deleteMultipleCommand]

#End of Extract#

---

==== Justification of 1st Enhancement

As TheYellowPage is designed with the typical office worker/Human Resource agent in mind, the features implemented are meant to make their work processes more efficient.

The original delete command only allows the user to delete one contact at a time. While feasible for the average user, it becomes a cumbersome process for the HR agent who has to deal with a massive number of contacts.

The DeleteMultipleCommand feature allows HR agents to clear off multiple contacts off their company's address book quickly, without having to clear the entire list.

==== Implementation of 1st Enhancement

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=deleteMultipleCommand]

#End of Extract#

---

=== 2nd Enhancement added: Find Command

==== External behaviour
---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=FindCommand]

#End of Extract#

---

=== Justification of 2nd Enhancement

As TheYellowPage is designed with the typical office worker/Human Resource agent in mind, the features implemented are meant to make their work processes more efficient.

The original find command only allows the user to find the contact by their name. However, when taken into context of the HR agent, the HR agent may sometimes only know a contact by their company name, company address or company phone number. Thus, finding a contact by name may not be as feasible.

The new Find Command feature allows HR agents to find the contacts they want via their name, address, number, email, occupation, company name or company website. This is more efficient as the HR agent will be able to find the contact they want more easily.

=== Implementation of 2nd Enhancement

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=FindCommand]

#End of Extract#

---

=== Enhancement Proposed: Add command `FindByExactAddress`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Updated the GUI background image (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
