= Victoria Lim Yan Hui - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Google Maps Browser

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=browser]

#End of Extract#

---

==== Justification

Since Ark is meant to assist in deliveries, it is necessary for Ark to have a Google Maps browser to show to users
the exact location of parcel delivery addresses.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=browser]

#End of Extract#

---

=== Enhancement Added: Tab Command

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tabs]

#End of Extract#

---

==== Justification

To improve usability for users of Ark to be able to quickly search between the different parcel statuses.
A Tab function would enable users of Ark to easily switch between different parcel lists of differing parcel statuses.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tabs]

#End of Extract#

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Changed the UI layout of MainWindow
(Pull requests https://github.com/CS2103AUG2017-T16-B1/main/pull/98[#98])

* Changed the UI layout of ParcelList and ParcelCard
(Pull requests https://github.com/CS2103AUG2017-T16-B1/main/pull/100[#100])

== Project: Modulus

{Optionally (not graded), you may include other projects in your portfolio.}
