= Wyn K Heng - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Bluebird
Bluebird is a desktop based organisational tool for the working parent on the go. Bluebird is suitable
for a variety of day-to-day management tasks, including managing appointments for both yourself and your
child, and also organising the contact information from your Address Book. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 15 kLoC. +

This project portfolio serves to provide an insight into how Wyn K Heng has contributed to project Bluebird. Included
in this portfolio are the enhancements, features, tests and proposed enhancements that Wyn K Heng has contribued to the project.

*Code contributed*: [[https://github.com/CS2103AUG2017-T15-B4/main/blob/master/collated/main/wynkheng.md[Functional code]] [https://github.com/CS2103AUG2017-T15-B4/main/blob/master/collated/test/wynkheng.md[Test code]]

=== Enhancement Added: Undo/Redo

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=undoredo]

#End of Extract#

---

==== Justification

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=undoredo]

#End of Extract#

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
