= Zhan Yu - Project Portfolio
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

ifdef::env-github[]
https://cs2103aug2017-w11-b2.github.io/main/team/ZhanYu.html[Please click here to view portfolio.]
endif::[]

ifndef::env-github[]
This is my portfolio page primarily for showcasing my contributions to the project, Rolodex.

This is not my full portfolio. To view my full portfolio, visit https://zy-ang.github.io/Portfolio[https://zy-ang.github.io/Portfolio].

== Project: Rolodex

include::../../README.adoc[tag=applicationDescription]

*Code contributed*:

* https://github.com/CS2103AUG2017-W11-B2/main/blob/master/collated/main/ZY-Ang.md[Functional Code]
* https://github.com/CS2103AUG2017-W11-B2/main/blob/master/collated/test/ZY-Ang.md[Tests]
* https://github.com/CS2103AUG2017-W11-B2/main/blob/master/collated/main/ZY-Ang-pages.md[Pages]

=== Enhancement Added: Find by close words (fuzzy searching) and find by tags

==== For the User

---

include::../UserGuide.adoc[leveloffset=2,tag=find]

---

==== Why would we need this?

Users may sometimes key commands too quickly or forget the names of their contacts.
This enhancement allows them to find contacts by close name words or by tags previously assigned to make finding contacts in the Rolodex a lot easier.

==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=2,tag=findClose]

---

=== Enhancement Added: Sort

==== For the User

---

include::../UserGuide.adoc[leveloffset=2,tag=list]
include::../UserGuide.adoc[leveloffset=2,tag=find]

---

==== Why would we need this?

Users may sometimes have too many contacts in a listing.
This enhancement allows them to find contacts quickly by sorting the displayed list of persons.
Users can operate on a sorted list for longer displayed lists via `list` or `find` command.

==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=2,tag=sorting]

---

=== Enhancement Added: Open existing file and Create new file commands

==== For the User

---

include::../UserGuide.adoc[leveloffset=2,tag=openfile]
include::../UserGuide.adoc[leveloffset=2,tag=newfile]

---

==== Why would we need this?

Users may want to work on a different group of data for different purposes.
Users with too many contacts can also create a separate database for dividing up the contacts into smaller,
more manageable sizes.

==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=2,tag=openNew]

---

=== Enhancement Improved: `java.util.Set` implementation for command abbreviations

==== Why would we need this?

Using constants to manually check if a command word belongs to a particular command is extremely tedious for both
developers and users. In addition, using constants forces the program to have to check through all possible command
abbreviations belonging to a command word in the worst case. A java `HashSet` takes care of these problems by improving
access time and improves manageability of the codebase.

==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=2,tag=commandAbbreviations]

---

=== Enhancement Added: Search Highlighting in HelpWindow

==== Why would we need this?

JavaFx's native WebView does not allow the user to easily search a html document, putting it on a subpar standard to modern
web browsers. Implementing a search feature in the help window will allow the user to search for terms in the user guide with ease.

==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=2,tag=helpWindowHighlight]

---

=== Enhancement Added: Suggesting Commands for Typos

==== For the User

---

include::../UserGuide.adoc[leveloffset=2,tag=suggestion]

---

==== Why would we need this?

Users may find it too much of a hassle to remember many of the syntaxes required by Rolodex such as `n/`, `r/`, etc.
Suggesting commands for such occasions would give the user a shallow learning curve and improve user experience significantly.

==== Implementation

---

include::../DeveloperGuide.adoc[leveloffset=2,tag=suggestion]

---

=== Enhancement Proposed: Markdown/HTML parser

To replace the content field of the note/remark command with 'rich-text', to be displayed on the browser panel.

=== Other contributions

* Added continuous integration tools using https://travis-ci.org/CS2103AUG2017-W11-B2/main[Travis CI],
https://ci.appveyor.com/project/ZY-Ang/main[AppVeyor],
https://coveralls.io/github/CS2103AUG2017-W11-B2/main?branch=master[Coveralls] and
https://www.codacy.com/app/ZY-Ang/main/dashboard[Codacy].
* Added a simple navbar to the github pages for ease of navigation.
* Managed projects and devOps.

== Project: https://zy-ang.github.io/AutoNameGenerator/[AutoNameGenerator]

== Other projects

You can view my full portfolio https://zy-ang.github.io/Portfolio[here].

endif::[]

ifndef::env-github[]
include::../NavigationMenu.adoc[]
endif::[]
