package seedu.address.autocomplete.parser;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import seedu.address.autocomplete.AutoCompleteTestUtils;
import seedu.address.logic.commands.AddCommand;
import seedu.address.logic.commands.RedoCommand;
import seedu.address.logic.commands.RemarkCommand;
import seedu.address.logic.commands.RemoveTagCommand;

//@@author john19950730
public class AutoCompleteCommandParserTest {
    @Rule
    public ExpectedException thrown = ExpectedException.none();

    private final AutoCompleteCommandParser parser = new AutoCompleteCommandParser();

    @Test
    public void parseAutoCompleteCommandAllAlphabets() throws Exception {
        // no match
        AutoCompleteTestUtils.assertParserPossibilities("b", parser);

        // single match
        AutoCompleteTestUtils.assertParserPossibilities("a", parser,
                AddCommand.COMMAND_USAGE);

        // multiple match
        AutoCompleteTestUtils.assertParserPossibilities("r", parser,
                RedoCommand.COMMAND_USAGE,
                RemarkCommand.COMMAND_USAGE,
                RemoveTagCommand.COMMAND_USAGE);
    }

    /**
     * Tests the possibilities generated by the stub against the list of possibilities expected
     * @param stub test input
     * @param possibilities expected possibilities output
     */
    private void assertPossibilities(String stub, String... possibilities) {
        AutoCompleteTestUtils.assertEqualsPossibilities(stub, parser.parseForPossibilities(stub), possibilities);
    }

}
