= Sales Navigator - Testing Script

== Setup

=== Loading sample data
. Create a folder anywhere named "test".
. Copy `salesnavigator.jar` into the test folder.
. Create a folder within the test folder named "data".
. Copy sample data into the data folder.
. Rename sample data to `addressbook.xml`.

== Tests
=== Test 1 - Add command without optional parameters
Input: `add n/Jack Sparrow p/90923422 e/jacksparrow@pirate.com a/Caribbean Islands`

Expected result: New person added. Company, Position, Status, Note fields set to NIL. Priority set to L. No photo, tags or relationships.

=== Test 2 - Add command with optional parameters
Input: `add n/Davey Jones p/90921211 e/daveyjones@pirate.com a/Caribbean Islands c/Pirate Co. po/Captain s/Requires immediate follow up pr/H t/friends`

Expected result: New person added. Note field set to NIL. No photo or relationships.

=== Test 3 - Edit command
Input: `edit 1 n/Johnathan Doel no/Enjoys seafood and western restaurants. pr/M`

Expected result: Note and priority fields changed.

=== Test 4 - Delete command
Input: `delete 3`

Expected result: Person with index 3 removed from person list.

=== Test 5 - Find command
Input: `find Jack`

Expected result: Jack Sparrow only person on person list.

=== Test 5 - List command
Input: `list`

Expected result: All persons listed in person list.

=== Test 6 - Clear command
Input: `clear`

Expected result: Address book cleared of all persons and events.

=== Test 7 - Undo command
Input: `undo`

Expected result: Address book repopulated with all persons and events.

=== Test 8 - Redo command
Input: `redo`, `undo`

Expected result: Address book is cleared again, then repopulated again.

=== Test - CheckSchedule command

Input: `checkschedule`

Expected result:

* A Calendar view is shown in the main window
* The date and time headers are correct to the current week
* Each event pane corresponds to an existing event
* Upon clicking "last page" and "next page", it shows the last week and next
week's event respectively

Input: `eventadd n/test t/17/11/2017 1100-1200 d/This is a test p/7`

Expected result:

* The event, if successfully added, should be scheduled in the calendar

Input: `eventedit 1 t/16/11/2017 1100-1200`

Expected result:

* The new event, if successfully edited, should reflect the change correctly in
the
calendar

Input: `eventedit 1 n/test2`

Expected result:

* The new event, if successfully edited, should reflect the change correctly in
the
calendar

Input: `eventedit 1 d/new description`

Expected result:

* The new event, if successfully edited, should reflect the change correctly in
the
calendar

Input: `eventedit 1 p/3`

Expected result:

* The new event, if successfully edited, should reflect the change correctly in
the
calendar

Input: `eventdelete 1`

Expected result:

* The event, if successfully deleted, should be deleted from the calendar as
well

=== Test - UpdatePhoto command

Input: `updatephoto 1` and then choose an image file from your local
directory (must be jpg/png/jpeg file)

Expected behavior:

* After selecting an image file, the person identified by the index should
have his/her photo changed to the selected image.

=== Test - "Import Photo" button

Input: Click on any person in the person list, and on the detail page that
shows up, click the "import photo" button, and then choose an image file from
your local directory (must be jpg/png/jpeg file)

Expected behavior:

* After selecting an image file, the person should
have his/her photo changed to the selected image.

=== Test - "Repeat" command

Input: `repeat 1 10`

Expected behavior:

* The event identified by the index should have its `repeat period` changed
to 10

=== Test - recurring event scheduling

Input: `eventadd n/test t/13/11/2017 1100-1200 d/This is a test p/7`

Expected behavior:

* Two events will be added: one on 13/11/2017, another one on 20/11/2017

Input: `eventedit [index of the previously added event] t/12/11/2017
1100-1200`

Expected behavior:

* Two events will be added: one on 12/11/2017, another one on 19/11/2017

Input: `eventedit [index of the previously edited event] p/6`

Expected behavior:

* A new events will be added: on 18/11/2017



