= Blast! - Testing Script
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:repoURL: https://github.com/se-edu/addressbook-level4/tree/master

Legend:
`INPUTS` command to type (e.g. *select 1* means to execute ‘select 1’ in the command box) +
```
Expected results are contained here
```
=== Set up

. Download all documents (i.e. all the test files) uploaded on v1.5 release. +
. Create a folder named ‘Blast’ and place the .jar file in +
. Create a folder named ‘data’ at the root of ‘Blast’ folder +
. Create a folder named ‘avatars’ at the root of ‘Blast’ folder +
. Place the downloaded test image into `avatars` folder +
. Place the downloaded test documents into `data` folder +
. Launch the application

=== Add

`add` +
```
Invalid command format!
add or a: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL a/ADDRESS i/AVATAR IMAGE FILE [r/TAG]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 i/john_doe.png r/friends r/owesMoney
```

---
`add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 i/john_doe.png r/friends r/owesMoney` +
```
File path provided must point to a valid, readable image.
```

---
`add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 r/friends r/owesMoney` +
```
New person added: John Doe Phone: 98765432 Email: johnd@example.com Address: 311, Clementi Ave 2, #02-25 Comments: 311, Clementi Ave 2, #02-25 Appointments:  Tags: [owesMoney][friends]
```

---
`undo`
```
Undo success!
```

---
`add john`
```
Invalid command format!
add or a: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL a/ADDRESS i/AVATAR IMAGE FILE [r/TAG]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 i/john_doe.png r/friends r/owesMoney
```

---
`add n/John Doe`
```
Invalid command format!
add or a: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL a/ADDRESS i/AVATAR IMAGE FILE [r/TAG]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 i/john_doe.png r/friends r/owesMoney
```

---
`add n/John Doe p/98765432`
```
Invalid command format!
add or a: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL a/ADDRESS i/AVATAR IMAGE FILE [r/TAG]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 i/john_doe.png r/friends r/owesMoney
```

---
`add n/John Doe p/98765432 e/johnd@example.com`
```
Invalid command format!
add or a: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL a/ADDRESS i/AVATAR IMAGE FILE [r/TAG]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 i/john_doe.png r/friends r/owesMoney
```

---
`add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25`
```
New person added: John Doe Phone: 98765432 Email: johnd@example.com Address: 311, Clementi Ave 2, #02-25 Comments: 311, Clementi Ave 2, #02-25 Appointments:  Tags:
```

---
`add n/John Doe p/!!!!! e/johnd@example.com a/311, Clementi Ave 2, #02-25`
```
Phone numbers can only contain numbers, and should be at least 3 digits long
```

---
<!— Self note to team (delete when fixed): the warning message doesn’t seem right. I can create email with j@e —>
`add n/John Doe p/98765432 e/johnd!example.com a/311, Clementi Ave 2, #02-25`
```
Person emails should be 2 alphanumeric/period strings separated by '@'
```

=== Edit

`edit`
```
Invalid command format!
edit or e: Edits the details of the person identified by the index number used in the last person listing. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [i/AVATAR] [r/TAG]...
Example: edit 1 p/91234567 e/johndoe@example.com
```

---
`edit 1 p/91234567 e/johndoe@example.com`
```
Edited Person: Alex Yeoh Phone: 91234567 Email: johndoe@example.com Address: Blk 30 Geylang Street 29, #06-40 Comments: Blk 30 Geylang Street 29, #06-40 Appointments: 20/10/2017 10:10:50 Tags: [student]
```

---
`edit -1 p/91234567`
```
Invalid command format!
edit or e: Edits the details of the person identified by the index number used in the last person listing. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [i/AVATAR] [r/TAG]...
Example: edit 1 p/91234567 e/johndoe@example.com
```

=== Delete

`delete 7`
```
Deleted Person: John Doe Phone: 98765432 Email: johnd@example.com Address: 311, Clementi Ave 2, #02-25 Comments: 311, Clementi Ave 2, #02-25 Appointments:  Tags:
```

---
`delete -1`
```
Invalid command format!
delete: Deletes the person identified by the index number used in the last person listing.
Parameters: INDEX (must be a positive integer)
Example: delete 1
```

---
`delete 1000`
```
The person index provided is invalid
```

=== Merge

`merge abc`
```
File not found.
```

---
`merge data/personstoadd.txt`
```
Unable to convert file data.
```

---
`merge data/newfile.xml`
```
File merged successfully.
```

=== Find

`find`
```
Invalid command format!
find or f: Finds all persons whose names contain any of the specified keywords (case-insensitive) and displays them as a list with index numbers.
Parameters: PREFIX_PERSON_ATTRIBUTE/KEYWORD [MORE_KEYWORDS]... [MORE_PARAMETERS]...
Examples:
1) find n/alice bob charlie
2) find r/family friends
3) find n/alice bob charlie r/family friends
```

---
`find n/charlotte`
```
1 persons listed!
```

---
`find ap/15:50`
```
1 persons listed!
```
---
=== Export

`export`
```
Invalid command format!
export: export the address book to a chosen file type
Parameters: export .txt [PATH]
Example: export .txt C:/user/user/desktop
```

---

`export .txt C:/address book` (on Windows) +
`export .txt /Users/[YOUR USER NAME]/address book` (on MacOS)
`export .txt /address book (on Linux)
```
Successfully exported
```
Also please check that the respective path has an `addressbook.txt` file containing all contacts.

---

`export .txt`
```
Invalid command format!
export: export the address book to a chosen file type
Parameters: export .txt [PATH]
Example: export .txt C:/user/user/desktop
```

---

`export .txt C:\Windows` (on Windows only. Linux and MacOS do not apply)
```
Access denied
```

---

=== Email Login

*Note*: UI buttons will not update automatically if logged in (or out) from console. However, clicking the login button will update the login status accordingly.

`email_login`
```
Invalid command format!
email_login: log in with an email address
Parameters: email_login "[EMAIL]" "[PASSWORD]"
Example: email_login "example@gmail.com"" example password"
```

---

`email_login cs2103testacc@gmail.com "testpass"` +
`email_login cs2103testacc@gmail.com testpass` +
`email_login "cs2103testacc@gmail.com" testpass`
```
Invalid command format!
email_login: log in with an email address
Parameters: email_login "[EMAIL]" "[PASSWORD]"
Example: email_login "example@gmail.com"" example password"
```

---

`email_login "123@hotmail.com" "password"`

```
Log in failed: The email domain is not supported
```

---

`email_login "123hotmail" "password"`

```
The given email is not valid
```

---

`email_login "cs2103testacc@gmail.com" "wrongpass"`
```
Log in failed: It could be one of the following reasons:
1. Your Internet connection is not working
2. Your email and password combination is not correct
3. Allow less secure apps is not enable in your email
```

---

`email_login "cs2103testacc@gmail.com" "testpass"`
```
Successfully logged in as cs2103testacc@gmail.com
```

---

=== Email Send
*Before testing this section please enter this command `email_login "cs2103testacc@gmail.com" "testpass"`*

---

`email_send`
```
Invalid command format!
email_send: Send an email to one or more recipients
Requires an logged in email using email_login
Parameters: email_send "[RECIPIENTS]" "[TITLE]" "[BODY]"
Example: email_send "example@gmail.com;example2@yahoo.com" "Test" "Test Body"
```

---

`email_send cs2103testacc@gmail.com "Title" "Body"` +
`email_send "cs2103testacc@gmail.com" Title Body` +
`email_send cs2103testacc@gmail.com "Title" "Body"`

```
Invalid command format!
email_send: Send an email to one or more recipients
Requires an logged in email using email_login
Parameters: email_send "[RECIPIENTS]" "[TITLE]" "[BODY]"
Example: email_send "example@gmail.com;example2@yahoo.com" "Test" "Test Body"
```

---

`email_send "cs2103testacc@gmail.com" "Title" "Body"`

```
Successfully sent
```

---
*Please substitute `[ANY OF YOUR EMAIL]` with a suitable email address.*

`email_send "cs2103testacc@gmail.com;[ANY OF YOUR EMAIL]" "Title" "Body"`

```
Successfully sent
```
Also please check that you have received an email from cs2103testacc@gmail.com with correct title and body.

---

=== Email Logout

`email_logout`

```
Logged out
```

---

=== Find Without Matching Whole Keyword

`find_contain`

```
Invalid command format!
find_contain: Finds all persons whose name / phone / address / email contains the given string
Parameters: find_contain PREFIX_PERSON_ATTRIBUTE/STRING [MORE_PARAMETERS]...Examples:
1) find_contain n/david li p/91
2) find_contain e/gmail a/jurong
```

---

`find_contain n/David Beckham`

```
1 persons listed!
```

---

`find_contain n/avid`

```
2 persons listed!
```

---

`find_contain n/vi p/99`

```
2 persons listed
```
___



